---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: milvus

---
# etcd StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: milvus
spec:
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer
  clusterIP: None
  selector:
    app: etcd

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: milvus
spec:
  serviceName: etcd
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.5
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        env:
        - name: ETCD_NAME
          value: "etcd-0"
        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          value: "http://etcd-0.etcd:2380"
        - name: ETCD_LISTEN_PEER_URLS
          value: "http://0.0.0.0:2380"
        - name: ETCD_LISTEN_CLIENT_URLS
          value: "http://0.0.0.0:2379"
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: "http://etcd-0.etcd:2379"
        - name: ETCD_INITIAL_CLUSTER
          value: "etcd-0=http://etcd-0.etcd:2380"
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd-data
  volumeClaimTemplates:
  - metadata:
      name: etcd-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi

---
# MinIO StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: milvus
spec:
  ports:
  - port: 9000
    name: api
  - port: 9001
    name: console
  clusterIP: None
  selector:
    app: minio

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: milvus
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2023-03-20T20-16-18Z
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        env:
        - name: MINIO_ROOT_USER
          value: "minioadmin"
        - name: MINIO_ROOT_PASSWORD
          value: "minioadmin"
        volumeMounts:
        - name: minio-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: minio-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Gi

---
# Pulsar Deployment (简化版)
apiVersion: v1
kind: Service
metadata:
  name: pulsar
  namespace: milvus
spec:
  ports:
  - port: 6650
    name: pulsar
  selector:
    app: pulsar

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar
  namespace: milvus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulsar
  template:
    metadata:
      labels:
        app: pulsar
    spec:
      containers:
      - name: pulsar
        image: apachepulsar/pulsar:2.8.2
        command:
        - sh
        - -c
        - |
          bin/apply-config-from-env.py conf/standalone.conf && \
          bin/pulsar standalone
        ports:
        - containerPort: 6650
          name: pulsar
        - containerPort: 8080
          name: http

---
# Milvus Standalone Deployment
apiVersion: v1
kind: ConfigMap
metadata:
  name: milvus-config
  namespace: milvus
data:
  milvus.yaml: |
    etcd:
      endpoints:
        - etcd:2379
    minio:
      address: minio
      port: 9000
      accessKeyID: minioadmin
      secretAccessKey: minioadmin
      useSSL: false
      bucketName: milvus-bucket
    pulsar:
      address: pulsar
      port: 6650
    common:
      storageType: minio

---
apiVersion: v1
kind: Service
metadata:
  name: milvus
  namespace: milvus
spec:
  type: ClusterIP
  ports:
  - port: 19530
    targetPort: 19530
    name: grpc
  - port: 9091
    targetPort: 9091
    name: metrics
  selector:
    app: milvus

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus
  namespace: milvus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
    spec:
      containers:
      - name: milvus
        image: milvusdb/milvus:v2.3.3
        args:
        - milvus
        - run
        - standalone
        ports:
        - containerPort: 19530
          name: grpc
        - containerPort: 9091
          name: metrics
        env:
        - name: ETCD_ENDPOINTS
          value: "etcd:2379"
        - name: MINIO_ADDRESS
          value: "minio:9000"
        - name: PULSAR_ADDRESS
          value: "pulsar://pulsar:6650"
        volumeMounts:
        - name: milvus-config
          mountPath: /milvus/configs/milvus.yaml
          subPath: milvus.yaml
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
      volumes:
      - name: milvus-config
        configMap:
          name: milvus-config

---
# Ingress (可选)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: milvus-ingress
  namespace: milvus
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  ingressClassName: nginx
  rules:
  - host: milvus.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: milvus
            port:
              number: 19530