---
# Milvus 数据持久卷
apiVersion: v1
kind: PersistentVolume
metadata:
  name: milvus-data-pv
  labels:
    app: milvus
    type: data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /opt/dockerstore/milvus/data
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: milvus
      type: data

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
    spec:
      containers:
        - name: milvus
          image: milvusdb/milvus:v2.6.12
          command: ["milvus", "run", "standalone"]
          ports:
            - containerPort: 19530
              name: grpc
            - containerPort: 9091
              name: http
          env:
            - name: ETCD_ENDPOINTS
              value: "etcd:2379"
            - name: MINIO_ADDRESS
              value: "minio:9000"
            - name: MQ_TYPE
              value: "rocksmq"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"
            - name: MINIO_USE_SSL
              value: "false"
            - name: TZ
              value: "Asia/Shanghai"

          volumeMounts:
            - name: milvus-data
              mountPath: /var/lib/milvus
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"

          livenessProbe:
            httpGet:
              path: /healthz
              port: 9091
            initialDelaySeconds: 120
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /healthz
              port: 9091
            initialDelaySeconds: 120
            periodSeconds: 5

      volumes:
        - name: milvus-data
          persistentVolumeClaim:
            claimName: milvus-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: milvus
spec:
  type: NodePort
  ports:
    - port: 19530
      targetPort: 19530
      name: grpc
      nodePort: 31530 # 修改这里：指定一个 30000-32767 之间的端口
    - port: 9091
      targetPort: 9091
      nodePort: 31531
      name: http
  selector:
    app: milvus
