---
# 1. 创建 PersistentVolume (PV)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data-pv
  labels:
    app: mongodb
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /opt/dockerstore/mongodb/data
    type: DirectoryOrCreate

---
# 2. 创建 PersistentVolumeClaim (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: mongodb

---
# 3. 创建 ConfigMap (MongoDB 配置文件)
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: default
data:
  mongod.conf: |
    # MongoDB 配置文件
    storage:
      dbPath: /data/db
      engine: wiredTiger
      wiredTiger:
        engineConfig:
          cacheSizeGB: 0.5
    
    systemLog:
      # 日志输出 
      # destination: file
      # path: /var/log/mongodb/mongod.log
      logAppend: true
      verbosity: 0
    
    net:
      port: 27017
      bindIp: 0.0.0.0
      maxIncomingConnections: 100
    
    security:
      authorization: enabled
    
    # 性能优化
    operationProfiling:
      mode: slowOp
      slowOpThresholdMs: 100

---
# 4. 创建 Secret (MongoDB 用户密码)
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: mongodb123456

---
# 5. 创建 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: default
  labels:
    app: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        imagePullPolicy: IfNotPresent
        args:
          - --config
          - /etc/mongo/mongod.conf
        ports:
        - containerPort: 27017
          name: mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
        - name: mongodb-config
          mountPath: /etc/mongo/mongod.conf
          subPath: mongod.conf
        - name: mongodb-log
          mountPath: /var/log/mongodb
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-data-pvc
      - name: mongodb-config
        configMap:
          name: mongodb-config
          items:
          - key: mongod.conf
            path: mongod.conf
      - name: mongodb-log
        emptyDir: {}

---
# 7. 创建 Service (NodePort - 外部访问)
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-nodeport
  namespace: default
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30017
    protocol: TCP
    name: mongodb