apiVersion: v1
kind: Namespace
metadata:
  name: web-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-gin-app
  namespace: web-app
  labels:
    app: my-gin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-gin-app
  template:
    metadata:
      labels:
        app: my-gin-app
    spec:
      containers:
        - name: my-gin-app
          image: host.docker.internal:5001/my-gin-app:v1.0.0
          imagePullPolicy: Always
          command: ["./my-gin-app", "-v", "1.0.0"]
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: my-gin-app
  namespace: web-app
  labels:
    app: my-gin-app
spec:
  type: ClusterIP
  selector:
    app: my-gin-app
  ports:
    - name: http
      port: 82
      targetPort: 8080
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-gin-app
  namespace: web-app
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: app.k8s
      http:
        paths:
          - path: /gin(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: my-gin-app
                port:
                  number: 82

# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: Gateway
# metadata:
#   name: gin-gateway
#   namespace: web-app
# spec:
#   gatewayClassName: nginx
#   listeners:
#     - name: http
#       port: 82
#       protocol: HTTP
#       allowedRoutes:
#         namespaces:
#           from: Same

# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: gin-route
#   namespace: web-app
# spec:
#   parentRefs:
#     - name: gin-gateway
#   rules:
#     - matches:
#         - path:
#             type: PathPrefix
#             value: /
#       backendRefs:
#         - name: my-gin-app
#           port: 82
