apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-gin-app
  namespace: test
  labels:
    app: my-gin-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-gin-app
  template:
    metadata:
      labels:
        app: my-gin-app
    spec:
      containers:
        - name: my-gin-app
          image: localhost:32000/my-gin-app:v1.3
          imagePullPolicy: Always
          command: ["./my-gin-app", "-v", "1.3"]
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: my-gin-app
  namespace: test
  labels:
    app: my-gin-app
spec:
  type: ClusterIP
  selector:
    app: my-gin-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
