---
apiVersion: v1
kind: Namespace
metadata:
  name: web-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-express-app
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-express-app
  template:
    metadata:
      labels:
        app: my-express-app
    spec:
      containers:
        - name: my-express-app
          image: host.docker.internal:5001/my-express-app:v1.0.0
          ports:
            - containerPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-express-app
#   namespace: web-app
# spec:
#   selector:
#     app: my-express-app
#   type: NodePort
#   ports:
#     - port: 3000
#       targetPort: 3000
#       nodePort: 30003
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: my-express-app
  namespace: web-app
spec:
  type: ClusterIP
  selector:
    app: my-express-app
  ports:
    - name: http
      port: 83
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-express-app
  namespace: web-app
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: app.k8s
      http:
        paths:
          - path: /express(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: my-express-app
                port:
                  number: 83
