---
# 1. Secret：RabbitMQ 用户和密码
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: default
type: Opaque
data:
  # echo -n "rabbit" | base64
  RABBITMQ_DEFAULT_USER: cmFiYml0      # rabbit
  RABBITMQ_DEFAULT_PASS: UmFiYml0QDEyMzQ1Ng==  # Rabbit@123456（建议改成强密码）
  RABBITMQ_ERLANG_COOKIE: c2VjcmV0Y29va2llMTIzNDU2  # secretcookie123456

---
# 2. ConfigMap：RabbitMQ 集群配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: default
data:
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_peer_discovery_k8s].
  rabbitmq.conf: |
    # 集群配置
    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.node_cleanup.interval = 30
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    
    # 队列镜像配置（高可用）
    queue_master_locator = min-masters
    
    # 日志配置
    log.console = true
    log.console.level = info
    
    # 管理界面
    management.tcp.port = 15672
    
    # AMQP 端口
    listeners.tcp.default = 5672

---
# 3. ServiceAccount 和 RBAC（用于自动发现集群节点）
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rabbitmq
  namespace: default
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rabbitmq
  namespace: default
subjects:
- kind: ServiceAccount
  name: rabbitmq
  namespace: default
roleRef:
  kind: Role
  name: rabbitmq
  apiGroup: rbac.authorization.k8s.io

---
# 4. PersistentVolumes：每个副本单独挂载 hostPath
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-0
  labels:
    app: rabbitmq
    pv-index: "0"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/dockerstore/rabbitmq/data-0
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rabbitmq-storage

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-1
  labels:
    app: rabbitmq
    pv-index: "1"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/dockerstore/rabbitmq/data-1
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rabbitmq-storage

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-2
  labels:
    app: rabbitmq
    pv-index: "2"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/dockerstore/rabbitmq/data-2
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rabbitmq-storage

---
# 5. Headless Service：StatefulSet 内部通信
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: default
spec:
  clusterIP: None
  publishNotReadyAddresses: true  # 重要：允许未就绪的 Pod 被发现
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      name: amqp
    - port: 15672
      name: management
    - port: 4369
      name: epmd
    - port: 25672
      name: dist

---
# 6. ClusterIP Service：用于外部访问
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: default
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
    - port: 15672
      targetPort: 15672
      name: management
  type: ClusterIP

---
# 7. NodePort Service：用于开发测试
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
      nodePort: 31672
      name: amqp
    - port: 15672
      targetPort: 15672
      nodePort: 31673
      name: management

---
# 8. StatefulSet：3 副本 RabbitMQ 集群
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: default
spec:
  serviceName: "rabbitmq-headless"
  replicas: 3
  podManagementPolicy: Parallel  # 并行启动 Pod
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      serviceAccountName: rabbitmq
      terminationGracePeriodSeconds: 30
      
      initContainers:
      # 设置正确的文件权限和创建 .erlang.cookie
      - name: setup-permissions
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          # 设置目录权限
          chown -R 999:999 /var/lib/rabbitmq
          chmod 755 /var/lib/rabbitmq
          
          # 创建 .erlang.cookie 文件（如果不存在）
          if [ ! -f /var/lib/rabbitmq/.erlang.cookie ]; then
            echo "secretcookie123456" > /var/lib/rabbitmq/.erlang.cookie
          fi
          
          # 设置 cookie 文件权限为 600（只有所有者可读写）
          chown 999:999 /var/lib/rabbitmq/.erlang.cookie
          chmod 400 /var/lib/rabbitmq/.erlang.cookie
          
          echo "Permissions set successfully"
          ls -la /var/lib/rabbitmq/
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        securityContext:
          runAsUser: 0
      
      containers:
      - name: rabbitmq
        image: rabbitmq:4.0.5-management
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        - containerPort: 4369
          name: epmd
        - containerPort: 25672
          name: dist
        
        env:
        # Erlang Cookie（集群节点间通信密钥）
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_ERLANG_COOKIE
        
        # 默认用户和密码
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_PASS
        
        # 节点名称
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RABBITMQ_NODENAME
          value: "rabbit@$(MY_POD_NAME).rabbitmq-headless.default.svc.cluster.local"
        
        # 使用长主机名
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        
        # K8s 服务名称（用于自动发现）
        - name: K8S_SERVICE_NAME
          value: "rabbitmq-headless"
        - name: K8S_HOSTNAME_SUFFIX
          value: ".rabbitmq-headless.default.svc.cluster.local"
        
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        - name: config
          mountPath: /etc/rabbitmq
        
        # 健康检查
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - ping
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - check_running
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        
        # 资源限制
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      
      volumes:
      - name: config
        configMap:
          name: rabbitmq-config
          items:
          - key: rabbitmq.conf
            path: rabbitmq.conf
          - key: enabled_plugins
            path: enabled_plugins
  
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: rabbitmq-storage
      resources:
        requests:
          storage: 10Gi

---
# 9. Ingress：通过域名访问管理界面
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: public  # MicroK8s 使用 public
  rules:
    - host: rabbitmq.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq-service
                port:
                  number: 15672