---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-data-pv
  labels:
    app: etcd
    type: data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual # 必须与 PVC 的 storageClassName 一致
  hostPath:
    path: /opt/dockerstore/etcd
    type: DirectoryOrCreate # 如果目录不存在，自动创建
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: etcd
      type: data

---
# 2. 创建 Etcd StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  serviceName: etcd
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.5
          command:
            - /usr/local/bin/etcd
            - --name
            - $(POD_NAME)
            - --data-dir
            - /etcd-data
            - --listen-client-urls
            - http://0.0.0.0:2379
            - --advertise-client-urls
            - http://$(POD_NAME).etcd:2379
            - --initial-cluster
            - $(POD_NAME)=http://$(POD_NAME).etcd:2380
            - --initial-advertise-peer-urls
            - http://$(POD_NAME).etcd:2380
            - --listen-peer-urls
            - http://0.0.0.0:2380
            - --initial-cluster-token
            - tkh3c
            - --initial-cluster-state
            - new
            - --auto-compaction-retention
            - "1"
            - --quota-backend-bytes
            - "4294967296"

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 2379
            - containerPort: 2380
          volumeMounts:
            - name: etcd-data
              mountPath: /etcd-data
          livenessProbe:
            httpGet:
              path: /health
              port: 2379
            initialDelaySeconds: 30
            timeoutSeconds: 5
      volumes:
        - name: etcd-data
          persistentVolumeClaim:
            claimName: etcd-data-pvc # 引用上面创建的 PVC

---
# 3. 创建 Etcd Service (修正为 Headless)
apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  type: ClusterIP
  clusterIP: None # 必须是 None，保证 StatefulSet 域名解析正常
  ports:
    - name: client
      port: 2379
      targetPort: 2379
    - name: peer
      port: 2380
      targetPort: 2380
  selector:
    app: etcd
