---
# 1. 创建 PersistentVolume (PV) - 日志存储
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-logs-pv
  labels:
    app: elasticsearch
    type: logs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /opt/dockerstore/elasticsearch/logs
    type: DirectoryOrCreate

---
# 2. 创建 ConfigMap (Elasticsearch 配置)
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: default
data:
  elasticsearch.yml: |
    cluster.name: es-cluster
    network.host: 0.0.0.0

    discovery.seed_hosts:
      - elasticsearch-0.elasticsearch-headless.default.svc.cluster.local
      - elasticsearch-1.elasticsearch-headless.default.svc.cluster.local
      - elasticsearch-2.elasticsearch-headless.default.svc.cluster.local
    cluster.initial_master_nodes:
      - elasticsearch-0
      - elasticsearch-1
      - elasticsearch-2

    node.roles: [ master, data, ingest ]

    path.data: /usr/share/elasticsearch/data
    path.logs: /usr/share/elasticsearch/logs

    bootstrap.memory_lock: false
    http.port: 9200
    transport.port: 9300

    xpack.security.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false

    xpack.monitoring.collection.enabled: true

    http.cors.enabled: true
    http.cors.allow-origin: "*"
    http.cors.allow-headers: "X-Requested-With,Content-Type,Content-Length,Authorization"

  jvm.options: |
    -Xms1g
    -Xmx1g
    -XX:+UseG1GC
    -XX:G1ReservePercent=25
    -XX:InitiatingHeapOccupancyPercent=30
    -Des.networkaddress.cache.ttl=60
    -Des.networkaddress.cache.negative.ttl=10
    -XX:+AlwaysPreTouch
    -Xss1m
    -Djava.awt.headless=true
    -Dfile.encoding=UTF-8
    -Djna.nosys=true
    -XX:-OmitStackTraceInFastThrow
    -Dio.netty.noUnsafe=true
    -Dio.netty.noKeySetOptimization=true
    -Dio.netty.recycler.maxCapacityPerThread=0
    -Dlog4j.shutdownHookEnabled=false
    -Dlog4j2.disable.jmx=true
    -Xlog:gc*,gc+age=trace,safepoint:file=/usr/share/elasticsearch/logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m

---
# 3. 创建 Job - 初始化目录权限
apiVersion: batch/v1
kind: Job
metadata:
  name: es-init-permissions
  namespace: default
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init
        image: busybox:1.36
        command: ['sh', '-c']
        args:
          - |
            echo "初始化 Elasticsearch 数据目录..."
            mkdir -p /usr/share/elasticsearch/data
            mkdir -p /usr/share/elasticsearch/logs
            chown -R 1000:1000 /usr/share/elasticsearch
            chmod -R 755 /usr/share/elasticsearch
            echo "完成"
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: logs
          mountPath: /usr/share/elasticsearch/logs
      volumes:
      - name: data
        hostPath:
          path: /opt/dockerstore/elasticsearch/data
          type: DirectoryOrCreate
      - name: logs
        hostPath:
          path: /opt/dockerstore/elasticsearch/logs
          type: DirectoryOrCreate

---
# 4. 创建 PersistentVolumeClaim (PVC) - Logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-logs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: elasticsearch
      type: logs

---
# 5. 创建 Headless Service (用于集群发现)
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  namespace: default
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: elasticsearch
  ports:
  - port: 9300
    name: transport
    protocol: TCP

---
# 6. 创建 StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: default
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch-headless
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      - name: sysctl
        image: busybox:1.36
        command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        securityContext:
          privileged: true
      - name: fix-permissions
        image: busybox:1.36
        command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch && chmod -R 755 /usr/share/elasticsearch']
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      containers:
      - name: elasticsearch
        image: elasticsearch:8.19.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        - name: ELASTIC_PASSWORD
          value: "elastic123"
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: logs
          mountPath: /usr/share/elasticsearch/logs
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: config
          mountPath: /usr/share/elasticsearch/config/jvm.options
          subPath: jvm.options
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /_cluster/health?wait_for_status=yellow&timeout=5s
            port: 9200
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: es-logs-pvc
      - name: config
        configMap:
          name: es-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: manual
      resources:
        requests:
          storage: 30Gi
      selector:
        matchLabels:
          app: elasticsearch
          type: data

---
# 7. 创建 ClusterIP Service
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: default
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: ClusterIP
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
    name: http
  - port: 9300
    targetPort: 9300
    protocol: TCP
    name: transport

---
# 8. 创建 NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-nodeport
  namespace: default
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30920
    protocol: TCP
    name: http

---
# 9. 创建 Ingress (可选)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
  - host: es.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elasticsearch-service
            port:
              number: 9200
