apiVersion: v1
kind: PersistentVolume
metadata:
  name: rustfs-pv
  labels:
    app: rustfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /run/desktop/mnt/host/e/dockerstore/rustfs/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-pvc
  labels:
    app: rustfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: rustfs-pv
  resources:
    requests:
      storage: 5Gi
  selector:                  # 加这里
    matchLabels:
      app: rustfs
---
apiVersion: v1
kind: Secret
metadata:
  name: rustfs-secret
type: Opaque
stringData:
  RUSTFS_ACCESS_KEY: "rustfsadmin"
  RUSTFS_SECRET_KEY: "rustfsadmin"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustfs
  labels:
    app: rustfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustfs
  template:
    metadata:
      labels:
        app: rustfs
    spec:
      containers:
        - name: rustfs
          image: rustfs/rustfs:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
          env:
            - name: RUSTFS_VOLUMES
              value: /data/rustfs0
            - name: RUSTFS_ADDRESS
              value: ":9000"
            - name: RUSTFS_CONSOLE_ADDRESS
              value: ":9001"
            - name: RUSTFS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: rustfs-secret
                  key: RUSTFS_ACCESS_KEY
            - name: RUSTFS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: rustfs-secret
                  key: RUSTFS_SECRET_KEY
            - name: RUSTFS_CONSOLE_ENABLE
              value: "true"
            - name: RUSTFS_ALLOW_INSECURE_DEFAULT_CREDENTIALS
              value: "true"

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - curl -f http://localhost:9000/health && curl -f http://localhost:9001/health
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - curl -f http://localhost:9000/health && curl -f http://localhost:9001/health
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3


          volumeMounts:
            - name: rustfs-data
              mountPath: /data
            - name: rustfs-logs
              mountPath: /logs
      volumes:
        - name: rustfs-data
          persistentVolumeClaim:
            claimName: rustfs-pvc
        - name: rustfs-logs
          hostPath:
            path: /run/desktop/mnt/host/e/dockerstore/rustfs/logs
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: rustfs
  labels:
    app: rustfs
spec:
  type: NodePort
  selector:
    app: rustfs
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 31900
      protocol: TCP
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 31901
      protocol: TCP